/********************************************************************
* calibHdrDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error calibHdrDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablecalibHdrDict();
extern void G__cpp_setup_inheritancecalibHdrDict();
extern void G__cpp_setup_typetablecalibHdrDict();
extern void G__cpp_setup_memvarcalibHdrDict();
extern void G__cpp_setup_globalcalibHdrDict();
extern void G__cpp_setup_memfunccalibHdrDict();
extern void G__cpp_setup_funccalibHdrDict();
extern void G__set_cpp_environmentcalibHdrDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/sklin/Data/sklin/Data/Software/NuWa-trunk/NuWa-trunk/dybgaudi/RootIO/PerCalibReadoutEvent/PerCalibReadoutEvent/PerCalibReadoutHeader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__calibHdrDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__calibHdrDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__calibHdrDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__calibHdrDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__calibHdrDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__calibHdrDictLN_maplEstringcORootIOUserDataProxymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORootIOUserDataProxymUgRsPgRsPgR;
extern G__linked_taginfo G__calibHdrDictLN_maplEstringcOmaplEstringcORootIOUserDataProxymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORootIOUserDataProxymUgRsPgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOmaplEstringcORootIOUserDataProxymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcORootIOUserDataProxymUgRsPgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__calibHdrDictLN_RootIOBaseObject;
extern G__linked_taginfo G__calibHdrDictLN_PerTemporalDataObject;
extern G__linked_taginfo G__calibHdrDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__calibHdrDictLN_PerHeaderObject;
extern G__linked_taginfo G__calibHdrDictLN_vectorlEPerRefcOallocatorlEPerRefgRsPgR;
extern G__linked_taginfo G__calibHdrDictLN_reverse_iteratorlEvectorlEPerRefcOallocatorlEPerRefgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__calibHdrDictLN_PerCalibReadoutHeader;

/* STUB derived class for protected member access */
